### ISSUE TITLE
Any intent on adding runtime queries for editor support?

### ISSUE THREAD

**Issue by fenneltheloon** [nwhetsell/tree-sitter-lilypond#1]
Needed for syntax highlighting and indentation.

**Comment by nwhetsell** [comment]
It depends on the particulars. My understanding is that Tree-sitter supports [queries](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#queries) for syntax highlighting, local variables, and injected languages (but _not_ indentation), it’s up to individual text editors to determine which queries and highlight names they support, and each text editor does this a little differently. So, while it’s possible to add queries directly to this grammar, it’s not clear to me what can be added that will be supported by multiple text editors.

I have a [Nova](https://nova.app) extension that [includes queries](https://github.com/nwhetsell/nova-lilypond-extension/tree/main/LilyPond.novaextension/Queries) that might be adaptable to this grammar. Also, if you can share which text editor(s) you use and what Tree-sitter queries/highlights they support, that would help.

**Comment by fenneltheloon** [comment]
I use helix primarily, but this would be useful for neovim support outside of the existing plugin that does not play nice with the tree-sitter / lsp model for extensible editors that seems to be the standard these past few years. Any other editor that lets you configure tree-sitter grammars directly would need a set of queries to work with.

Sadly, there is no existing lsp for lilypond at the moment, so editor-specific support is all we have right now it seems.

Here is Helix's documentation for [textobject queries](https://docs.helix-editor.com/guides/textobject.html), [indentation queries](https://docs.helix-editor.com/guides/indent.html) (they do exist!), and [injection queries](https://docs.helix-editor.com/guides/injection.html) (this would be for recognizing Scheme in Lilypond or-although a separate issue-recognizing lilypond inside of a TeX document).

I imagine that the existing queries that you've written can be jigsaw puzzled around into proper support (except maybe for indentation) with not too much effort.

**Comment by nwhetsell** [comment]
Unfortunately, it looks most of Helix’s Tree-sitter queries are specific to Helix, and consequently unsuitable for inclusion with this grammar. Helix’s textobject and indent query files must be installed in a [particular folder of Helix](https://github.com/helix-editor/helix/tree/master/runtime/queries), so those queries would not work with Helix even they were included with this grammar. Injection queries are more or less a [Tree-sitter standard](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection), however, and I might attempt to at least move the [syntax highlighting queries from here](https://github.com/nwhetsell/nova-lilypond-extension/tree/main/LilyPond.novaextension/Queries) to this grammar.
